name: Terraform Deploy to AWS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-central-1

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.2

      # 3. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      # 4. Build Lambda zip for SOAR function
      - name: Build Lambda zip
        run: |
          # Zorg dat je lambda_function.py in dezelfde folder staat als deze workflow
          zip -r soar_function.zip lambda_function.py

      # 5. Terraform Init (S3 backend)
      - name: Terraform Init
        run: terraform init -input=false -upgrade

      # 6. Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # 7. Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan -input=false

      # 8. Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
